minimumReleaseAgeExcludePrune: true
minimumReleaseAgeExclude:
  - '@kikiutils/mongoose' # TODO: remove it
  - '@kikiutils/shared' # TODO: remove it
  - '@types/bun'
  - bun-types

trustPolicy: no-downgrade
shellEmulator: true

allowBuilds:
  msgpackr-extract: true
