minimumReleaseAgeExcludePrune: true
minimumReleaseAgeExclude:
  - '@types/bun'
  - bun-types

trustPolicy: no-downgrade
trustPolicyExclude:
  - why-is-node-running@3.2.2

shellEmulator: true

allowBuilds:
  msgpackr-extract: true
